name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk

      - name: Install Buildozer
        run: |
          pip install buildozer cython

      - name: FORCE clean environment
        run: |
          rm -rf ~/.buildozer ~/.android

      - name: Build APK
        run: |
          buildozer android debug
